# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lIhtZH0cnf6lcFhEf2zIbEXODnMBo-UZ
"""

from flask import Flask, render_template
from flask import request
from flask_ngrok import run_with_ngrok
import urllib.request
from fastai import *
from fastai.vision import * 

app = Flask(__name__)
run_with_ngrok(app)   

def load_model():
    path = './'
    learn = load_learner(path, 'export.pkl')
    return learn
model = load_model()
labels = ['Goku', 'Luffy', 'Naruto', 'Natsu']
images = ["https://cdn-www.comingsoon.net/assets/uploads/2021/05/dragon-ball.jpg",
          "https://i.pinimg.com/originals/4e/aa/b6/4eaab69fcf8d928738072cd355a980db.jpg",
          "https://static.zerochan.net/Uzumaki.Naruto.full.3291213.jpg",
          "https://bbts1.azureedge.net/images/p/full/2021/02/cc97eea8-abbf-47f5-a66a-652c6feacdc7.jpg"
          ]

@app.route("/")
def index():
    return render_template("index.html")

@app.route('/predict',methods=['POST'])
def predict():

  #url = request.form.name['image_upload']
  url = request.form['image_upload']
  urllib.request.urlretrieve(url,"local-img.jpg")
  img = open_image('local-img.jpg')
  val = int(model.predict(img)[1])
  im_show = images[val]
  output = labels[val]
  return render_template('result.html',im_show=im_show, prediction_text='Predicted hero is  {}'.format(output))

@app.errorhandler(500)
def wrong_url(e):
  return render_template('error.html')



if __name__ == "__main__":
  app.run()